---
title: "0. Pre-Workshop Setup"
author: "Michael Weisner"
date: "February 14, 2019"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Example Git Update]

1. [Install R](https://cran.r-project.org/)
2. [Download R Studio](https://www.rstudio.com/products/rstudio/download/)
3. [Use R Cheatsheets](https://www.rstudio.com/resources/cheatsheets/)
4. Download Federalist Dataset to your working directory here: [goo.gl/y5v6bx](goo.gl/y5v6bx)
5. Install Appropriate Packages with the following command:

```{r package installation1, eval=FALSE}
install.packages(c("tidyr", "tidyverse", "dplyr", "ggraph", "tidytext", "gutenbergr", "janeaustenr", "tm", "wordcloud", "topicmodels", "text2vec", "ggplot2", "igraph", "quanteda", "rmarkdown", "rtweet", "stringr", "Matrix", "ggthemes"))
```


You may also need devtools to install from github, with packages like widyr.

```{r package installation2, eval=FALSE}
install.packages("devtools")
library(devtools)
devtools::install_github("dgrtwo/widyr")
```

















